### ISSUE TITLE
ninja: build stopped; subcommand failed "memcpy" was not declared in this scope

### ISSUE THREAD

**Issue by johnny-wang16** [WKDSMRT/realsense-gstreamer#9]
encountered the following error while executing the command
 `sudo ninja -C build install`
Any suggestions on how to resolve it? I am running it on a Ubuntu 16.04 machine.

`ninja: Entering directory build'
[2/6] Compiling C++ object 'src/25a663...ealsensesrc@sha/gstrealsensesrc.cpp.o'
FAILED: src/25a6634@@gstrealsensesrc@sha/gstrealsensesrc.cpp.o 
c++ -Isrc/25a6634@@gstrealsensesrc@sha -Isrc -I../src -I/usr/local/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/orc-0.4 -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -fPIC -pthread -DHAVE_CONFIG_H -std=c++1z -MD -MQ 'src/25a6634@@gstrealsensesrc@sha/gstrealsensesrc.cpp.o' -MF 'src/25a6634@@gstrealsensesrc@sha/gstrealsensesrc.cpp.o.d' -o 'src/25a6634@@gstrealsensesrc@sha/gstrealsensesrc.cpp.o' -c ../src/gstrealsensesrc.cpp
In file included from ../src/gstrealsensesrc.cpp:53:0:
../src/rsmux.hpp: In static member function ‘static GstBuffer* RSMux::mux(rs2::frameset&, const RSHeader&, const GstRealsenseSrc*)’:
../src/rsmux.hpp:99:51: error: ‘memcpy’ was not declared in this scope
         memcpy(minfo.data, &header, sizeof(header));
                                                   ^
../src/rsmux.hpp: In static member function ‘static buf_tuple RSMux::demux(GstBuffer*, const RSHeader&)’:
../src/rsmux.hpp:153:42: error: ‘memcpy’ was not declared in this scope
         memcpy(cmap.data, cdata, color_sz);
                                          ^
[3/6] Compiling C++ object 'src/25a663...lsensesrc@sha/gstrealsensedemux.cpp.o'
FAILED: src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o 
c++ -Isrc/25a6634@@gstrealsensesrc@sha -Isrc -I../src -I/usr/local/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/orc-0.4 -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -fPIC -pthread -DHAVE_CONFIG_H -std=c++1z -MD -MQ 'src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o' -MF 'src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o.d' -o 'src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o' -c ../src/gstrealsensedemux.cpp
In file included from ../src/gstrealsensedemux.cpp:53:0:
../src/rsmux.hpp: In static member function ‘static GstBuffer* RSMux::mux(rs2::frameset&, const RSHeader&, const GstRealsenseSrc*)’:
../src/rsmux.hpp:99:51: error: ‘memcpy’ was not declared in this scope
         memcpy(minfo.data, &header, sizeof(header));
                                                   ^
../src/rsmux.hpp: In static member function ‘static buf_tuple RSMux::demux(GstBuffer*, const RSHeader&)’:
../src/rsmux.hpp:153:42: error: ‘memcpy’ was not declared in this scope
         memcpy(cmap.data, cdata, color_sz);
                                          ^
../src/gstrealsensedemux.cpp: In function ‘GstFlowReturn gst_rsdemux_demux_video(GstRSDemux*, GstBuffer*)’:
../src/gstrealsensedemux.cpp:431:8: error: expected unqualified-id before ‘[’ token
   auto [colorbuf, depthbuf, imubuf] = RSMux::demux(buffer, header);
        ^
../src/gstrealsensedemux.cpp:437:33: error: ‘colorbuf’ was not declared in this scope
   gst_buffer_add_realsense_meta(colorbuf, *rsmeta->cam_model, *rsmeta->cam_serial_number,rsmeta->exposure,*rsmeta->json_descr);
                                 ^
../src/gstrealsensedemux.cpp:438:33: error: ‘depthbuf’ was not declared in this scope
   gst_buffer_add_realsense_meta(depthbuf, *rsmeta->cam_model, *rsmeta->cam_serial_number,rsmeta->exposure,*rsmeta->json_descr);
                                 ^
../src/gstrealsensedemux.cpp:439:6: error: ‘imubuf’ was not declared in this scope
   if(imubuf != nullptr && rsdemux->imusrcpad != nullptr)
      ^
../src/gstrealsensedemux.cpp:451:6: error: ‘imubuf’ was not declared in this scope
   if(imubuf != nullptr && rsdemux->imusrcpad != nullptr)
      ^
ninja: build stopped: subcommand failed.`

**Comment by TimConnelly** [comment]
I was not able to reproduce the error on Ubuntu 18.04. What was the output of the `meson . build` step? Which version of GCC are you using(`g++ --version`)? 

Can you build the issue9 branch? https://github.com/WKDSMRT/realsense-gstreamer/tree/issue9-memcpy-not-in-scope

**Comment by johnny-wang16** [comment]
My GCC version is 5.4.0 . 
The output of the `meson . build` step is the following:
`Version: 0.54.1
Source dir: /home/johnny/realsense-gstreamer
Build dir: /home/johnny/realsense-gstreamer/build
Build type: native build
Project name: realsensesrc
Project version: 0.1.0
C++ compiler for the host machine: c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
C++ linker for the host machine: c++ ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gstreamer-1.0 found: YES 1.16.0
Configuring config.h using configuration
Run-time dependency gstreamer-video-1.0 found: YES 1.16.0
Run-time dependency gstreamer-audio-1.0 found: YES 1.16.0
Run-time dependency realsense2 found: YES 2.34.0
Build targets in project: 1

Found ninja-1.10.0.git at /usr/local/bin/ninja`

I tried to build the issue9 branch but get the following error:
`ninja: Entering directory `build'
[3/6] Compiling C++ object 'src/25a663...lsensesrc@sha/gstrealsensedemux.cpp.o'
FAILED: src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o 
c++ -Isrc/25a6634@@gstrealsensesrc@sha -Isrc -I../src -I/usr/local/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/orc-0.4 -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g -fPIC -pthread -DHAVE_CONFIG_H -std=c++1z -MD -MQ 'src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o' -MF 'src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o.d' -o 'src/25a6634@@gstrealsensesrc@sha/gstrealsensedemux.cpp.o' -c ../src/gstrealsensedemux.cpp
../src/gstrealsensedemux.cpp: In function ‘GstFlowReturn gst_rsdemux_demux_video(GstRSDemux*, GstBuffer*)’:
../src/gstrealsensedemux.cpp:431:8: error: expected unqualified-id before ‘[’ token
   auto [colorbuf, depthbuf, imubuf] = RSMux::demux(buffer, header);
        ^
../src/gstrealsensedemux.cpp:437:33: error: ‘colorbuf’ was not declared in this scope
   gst_buffer_add_realsense_meta(colorbuf, *rsmeta->cam_model, *rsmeta->cam_serial_number,rsmeta->exposure,*rsmeta->json_descr);
                                 ^
../src/gstrealsensedemux.cpp:438:33: error: ‘depthbuf’ was not declared in this scope
   gst_buffer_add_realsense_meta(depthbuf, *rsmeta->cam_model, *rsmeta->cam_serial_number,rsmeta->exposure,*rsmeta->json_descr);
                                 ^
../src/gstrealsensedemux.cpp:439:6: error: ‘imubuf’ was not declared in this scope
   if(imubuf != nullptr && rsdemux->imusrcpad != nullptr)
      ^
../src/gstrealsensedemux.cpp:452:6: error: ‘imubuf’ was not declared in this scope
   if(imubuf != nullptr && rsdemux->imusrcpad != nullptr)
      ^
[4/6] Compiling C++ object 'src/25a663...alsensesrc@sha/gstrealsensemeta.cpp.o'
ninja: build stopped: subcommand failed.`

**Comment by johnny-wang16** [comment]
I updated my g++/gcc version to 7.5.0 and it solves the problem
